#!/bin/bash

# Smart Camera Test Summary
# Run this after APK is installed to test all features

echo "🧪 ReceiptKeeper Smart Camera Test Plan"
echo "========================================"
echo ""

echo "📋 Prerequisites:"
echo "✓ APK installed on device"
echo "✓ Camera permission granted"
echo "✓ Sample receipt/invoice ready"
echo ""

echo "🔍 Test 1: OCR Extraction"
echo "-------------------------"
echo "1. Open app → Tap 'Capture Receipt'"
echo "2. Choose 'Smart Document Scan'"
echo "3. Point camera at receipt"
echo "4. Verify OCR text appears in real-time"
echo "5. Tap capture button"
echo ""
echo "Expected: Text extracted, fields parsed"
echo "Check: Console logs for extracted fields"
echo ""

echo "✏️ Test 2: Field Editing"
echo "-------------------------"
echo "1. After capture, ReceiptPreviewScreen should appear"
echo "2. Verify extracted fields displayed:"
echo "   - Date"
echo "   - Vendor name"
echo "   - Total amount"
echo "   - Tax amount"
echo "   - Invoice number"
echo "3. Check confidence indicators (bars)"
echo "4. Edit any low-confidence field (yellow)"
echo "5. Tap 'Save Receipt'"
echo ""
echo "Expected: Data saved to database with OCR fields"
echo ""

echo "💾 Test 3: Database Verification"
echo "---------------------------------"
echo "Use adb shell or app logs to verify:"
echo ""
echo "adb shell"
echo "cd /data/data/com.receiptkeeper/databases"
echo "sqlite3 ReceiptKeeper.db"
echo "SELECT vendor_name, total_amount, invoice_number FROM receipts ORDER BY id DESC LIMIT 1;"
echo ""
echo "Expected: New receipt with OCR data populated"
echo ""

echo "📄 Test 4: PDF Generation"
echo "--------------------------"
echo "Run from Node.js (if possible) or via app UI (future):"
echo ""
echo "node scripts/testPdfGeneration.js"
echo ""
echo "Expected: Monthly PDF generated in:"
echo "  /storage/emulated/0/Android/data/com.receiptkeeper/files/ReceiptKeeper/PDFs/"
echo ""

echo "📊 Test 5: End-to-End Workflow"
echo "-------------------------------"
echo "1. Scan 3 different receipts"
echo "2. Edit and save each one"
echo "3. View in main screen list"
echo "4. Generate monthly PDF"
echo "5. Open PDF and verify:"
echo "   - Summary table with all 3 receipts"
echo "   - Individual pages with data + images"
echo ""

echo "🐛 Known Issues to Watch For"
echo "-----------------------------"
echo "⚠️ Low confidence on handwritten text"
echo "⚠️ Date format ambiguity (EU vs US)"
echo "⚠️ Multiple amounts on receipt (taxes, tips)"
echo "⚠️ Vendor name extraction from logo text"
echo ""

echo "📝 Test Results Log"
echo "-------------------"
echo "Test 1 (OCR): [ ]"
echo "Test 2 (Edit): [ ]"
echo "Test 3 (DB): [ ]"
echo "Test 4 (PDF): [ ]"
echo "Test 5 (E2E): [ ]"
echo ""

echo "✅ Success Criteria:"
echo "- At least 70% field extraction accuracy"
echo "- All fields editable and saveable"
echo "- PDF generates without errors"
echo "- No app crashes during workflow"
echo ""

echo "Run completed. Follow test plan above."
